name: forgejo

services:
  forgejo_db:
    container_name: forgejo_db
    environment:
      POSTGRES_DB: forgejo
      POSTGRES_USER: forgejo
      TZ: Europe/Berlin
    env_file:
      - /run/secrets/forgejo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U forgejo"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres:17.4-alpine
    networks:
      forgejo:
        ipv4_address: 10.10.14.20
    restart: unless-stopped
    stop_grace_period: 2m
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/bucket/forgejo/db:/var/lib/postgresql/data

  forgejo_app:
    container_name: forgejo_app
    depends_on:
      forgejo_db:
        condition: service_healthy
    environment:
      FORGEJO____APP_NAME: Forgejo
      FORGEJO__database__DB_TYPE: postgres
      FORGEJO__database__HOST: forgejo_db:5432
      FORGEJO__database__NAME: forgejo
      FORGEJO__database__USER: forgejo
      FORGEJO__server__LFS_START_SERVER: "true"
      FORGEJO__server__DOMAIN: forgejo.welles.app
      FORGEJO__server__ROOT_URL: https://forgejo.welles.app
      FORGEJO__server__START_SSH_SERVER: "true"
      FORGEJO__server__SSH_PORT: "22"
      FORGEJO__server__SSH_LISTEN_PORT: "2222"
      FORGEJO__server__SSH_DOMAIN: forgejo.welles.app
      FORGEJO__lfs__PATH: /lfs
      FORGEJO__mailer__ENABLED: "true"
      FORGEJO__mailer__PROTOCOL: smtp+starttls
      FORGEJO__mailer__SMTP_ADDR: smtp.ionos.de
      FORGEJO__mailer__SMTP_PORT: "587"
      FORGEJO__mailer__FROM: "Forgejo <noreply@welles.email>"
      FORGEJO__mailer__USER: noreply@welles.email
      FORGEJO__security__INSTALL_LOCK: "true"
      FORGEJO__session__PROVIDER: db
      FORGEJO__service__DISABLE_REGISTRATION: "true"
      TZ: Europe/Berlin
    env_file:
      - /run/secrets/forgejo
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    image: codeberg.org/forgejo/forgejo:14.0.3
    networks:
      forgejo:
        ipv4_address: 10.10.14.10
    ports:
      - 50140:3000/tcp
      - 50141:2222/tcp
    restart: unless-stopped
    stop_grace_period: 2m
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/bucket/forgejo/app:/data
      - /mnt/tank/forgejo_lfs:/lfs

networks:
  forgejo:
    name: forgejo
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 10.10.14.0/24
