name: kasm

services:
  kasm:
    container_name: kasm
    environment:
      KASM_PORT: 443
      TZ: Europe/Berlin
    env_file:
      - /run/secrets/kasm
    healthcheck:
      test: ["CMD-SHELL", "curl -fks https://localhost:443/api/public/running_config || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 300s
    image: lscr.io/linuxserver/kasm:1.18.1
    networks:
      kasm:
        ipv4_address: 10.10.7.10
    ports:
      - 50070:3000/tcp
      - 50071:443/tcp
    privileged: true
    restart: unless-stopped
    stop_grace_period: 2m
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/bucket/apps/kasm/data:/opt:rw

networks:
  kasm:
    name: kasm
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 10.10.7.0/24
