version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/modules/stacks/ark_server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/modules/stacks/dockge"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/modules/stacks/drydock"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/modules/stacks/guacamole"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/modules/stacks/jellyfin"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/modules/stacks/kasm"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/modules/stacks/navidrome"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/modules/stacks/nextcloud"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/modules/stacks/webtop"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/modules/stacks/windows"
    schedule:
      interval: "weekly"
